openapi: 3.0.0
info:
  title: Nest.js Hello World API
  description: A simple Nest.js API that returns "Hello World"
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /hello:
    get:
      summary: Retrieve a greeting message
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
              example: Hello World
